# Generated by Django 5.0.7 on 2024-08-05 16:27

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='ایمیل')),
                ('activation_code', models.CharField(blank=True, max_length=20, verbose_name='کد فعال سازی')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال بودن')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین بودن')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='مدیر بودن')),
                ('user_type', models.CharField(choices=[('backend', 'Backend User'), ('frontend', 'Frontend User'), ('user', 'User')], default='user', max_length=20, verbose_name='نوع کاربر')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت نام')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='شماره همراه')),
                ('gender', models.CharField(choices=[('male', 'آقا'), ('female', 'خانوم'), ('other', 'دیگر')], default='دیگر', max_length=20, verbose_name='جنسیت')),
                ('bio', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('image', models.ImageField(blank=True, upload_to=users.models.upload_to, verbose_name='عکس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserProfile_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تکمیلی کاربر',
                'verbose_name_plural': 'تکمیلی کاربران',
            },
        ),
    ]
