# Generated by Django 5.0.7 on 2024-08-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_activation_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'Users Profile'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('backend', 'Backend User'), ('frontend', 'Frontend User'), ('admin', 'Admin User'), ('client', 'Client')], default='user', max_length=20, verbose_name='User Type'),
        ),
    ]
