# Generated by Django 5.0.7 on 2024-08-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('backend', 'Backend User'), ('frontend', 'Frontend User'), ('admin', 'Admin User'), ('client', 'Client')], default='client', max_length=20, verbose_name='User Type'),
        ),
    ]
