# Generated by Django 5.0.7 on 2024-08-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('backend', 'Backend User'), ('frontend', 'Frontend User'), ('admin', 'Admin User'), ('client', 'Client')], default='client', max_length=20, verbose_name='User Type'),
        ),
    ]
