# Generated by Django 5.0.7 on 2024-08-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'آقا'), ('female', 'خانوم'), ('other', 'دیگر')], default='other', max_length=20, verbose_name='Gender'),
        ),
    ]
