# Generated by Django 5.0.7 on 2024-09-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_inpersoncustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inpersoncustomer',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Phone Number'),
        ),
    ]
