# Generated by Django 5.0.7 on 2024-09-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Holiday Date')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('expired', 'Expired')], default='pending', max_length=10, verbose_name='Order Status'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Price'),
        ),
    ]
