# Generated by Django 5.0.7 on 2024-09-04 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_order_created_at_alter_order_total_amount'),
        ('users', '0008_inpersoncustomer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='in_person_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_person_customers_Order', to='users.inpersoncustomer', verbose_name='In-Person Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='online_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_customers_Order', to=settings.AUTH_USER_MODEL, verbose_name='Online Customer'),
        ),
    ]
