# Generated by Django 5.0.7 on 2024-09-16 05:39

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_orderitem_price_orderitem_grand_total_and_more'),
        ('users', '0009_alter_inpersoncustomer_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percentage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50)], verbose_name='Percentage'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['code'], name='main_discou_code_6ace07_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['is_active'], name='main_discou_is_acti_2d2847_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['start_date'], name='main_discou_start_d_515b67_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['expiry_date'], name='main_discou_expiry__7c9851_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['food'], name='main_food_food_72515a_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['category'], name='main_food_categor_7adc01_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['price'], name='main_food_price_416d07_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['slug'], name='main_food_slug_3a62d9_idx'),
        ),
        migrations.AddIndex(
            model_name='foodcategory',
            index=models.Index(fields=['category'], name='main_foodca_categor_5d4ef1_idx'),
        ),
        migrations.AddIndex(
            model_name='foodcategory',
            index=models.Index(fields=['parent'], name='main_foodca_parent__ab3820_idx'),
        ),
        migrations.AddIndex(
            model_name='foodcategory',
            index=models.Index(fields=['slug'], name='main_foodca_slug_71ba76_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type'], name='main_order_order_t_015705_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_method'], name='main_order_payment_e2f9fd_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='main_order_payment_940ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='main_order_created_a818a5_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['food'], name='main_orderi_food_id_30bc99_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='main_orderi_order_i_fcf220_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user'], name='main_reserv_user_id_3227e1_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['start_date'], name='main_reserv_start_d_efb48e_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['end_date'], name='main_reserv_end_dat_b005c0_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['number_of_tables'], name='main_reserv_number__6f02f8_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['is_approved'], name='main_reserv_is_appr_90c495_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['order_status'], name='main_reserv_order_s_7b647f_idx'),
        ),
    ]
